### ISSUE TITLE
OnItemClickListener - Isometric.Item isn't public

### ISSUE THREAD

**Issue by bestog** [FabianTerhorst/Isometric#2]
**MainActivity.java**
```java
        isometricView.setClickListener(new IsometricView.OnItemClickListener() {
            @Override
            public void onClick(@NonNull Isometric.Item item) {

            }
        });
```
I cannot access Isometric.Item (error: Item is not public in Isometric; cannot be accessed from outside package). This is a feature or bug? :)

PS: Your library is awesome. 👍

**Comment by FabianTerhorst** [comment]
Hi,

thanks for the bug report, please test with  'io.fabianterhorst:Isometric:0.0.6.5'
